project:
  type: website
  output-dir: docs

website:
  title: "Анна Пирогова — Data Scientist & Health Economist"
  navbar:
    left:
      - text: Обо мне
        href: index.qmd
      - text: Портфолио
        href: portfolio.qmd
      - text: Сертификаты
        href: certificates.qmd        
      - text: Исследования
        href: research_academic_work.qmd
      - text: Контакты
        href: contact.qmd 
    right:
      - text: EN English
        href: https://anna-pirogova.github.io/anna-pirogova-english/
  page-footer: 
    center: "© 2025 Anna Pirogova"

format:
  html:
    theme: cosmo
    mainfont: "Lato"
    monofont: "JetBrains Mono"
    include-in-header: _includes/head.html
    css: styles.css
    toc: true
